In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

p = 0.5 # probabilidad de perder un dato
sample_size = np.array([10, 100, 1000, 10000])
redo_experiment = 300
bias_array = []

data = np.random.normal(size= sample_size.max())

data
    
    

array([ 0.27461965, -1.48771892,  1.88606738, ..., -0.20169817,
       -1.07386686,  0.83791313])

In [8]:
missing = np.random.binomial(1, p, 10).astype(bool)
missing

array([ True, False,  True,  True,  True, False, False,  True, False,
       False])

In [7]:
sample = data[:10]
sample

array([ 0.27461965, -1.48771892,  1.88606738, -0.65396462, -0.1275926 ,
        0.54890552, -1.72346145,  0.8197359 ,  1.42503711, -0.31387526])

In [11]:
sample[~missing]

array([-1.48771892,  0.54890552, -1.72346145,  1.42503711, -0.31387526])

In [12]:
for n in sample_size:
    sample = data[:n]

    bias = np.zeros( redo_experiment )
    for i in range(redo_experiment):
        # por probabilidad no tendremos datos en ciertos lados
        lost_data = np.random.binomial(1, p, n).astype(bool)
        sample_observada = sample[~lost_data]

        # producto de no ser random sampling, no tendremos una seccion
        sample_observada = sample_observada[ sample_observada > 0]
        bias[i] = sample_observada.mean()
    bias_array.append(bias)

C:\Users\fbien.DESKTOP-6FMEAR7\AppData\Local\Temp\ipykernel_10576\3321727386.py:12: RuntimeWarning: Mean of empty slice.
  bias[i] = sample_observada.mean()
c:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [17]:
print(f"{np.sum(np.isnan(bias_array))} # veces que quedamos con Nan")

11 # veces que quedamos con Nan


In [27]:
lista = [10,20,30,40,50]
numeros = np.array([i for i in range(10,50)])
print(numeros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [31]:
np.split(numeros, 5) # 5 cantidad de sub arrays

[array([10, 11, 12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23, 24, 25]),
 array([26, 27, 28, 29, 30, 31, 32, 33]),
 array([34, 35, 36, 37, 38, 39, 40, 41]),
 array([42, 43, 44, 45, 46, 47, 48, 49])]

## Plotting