# SVD
Se trata de descomponer una matriz en otras 3, $U$ y $V$ son unitarias:
$U \, U^T = I$

$$
C = U \Sigma V^T
$$

$U$ es la matrix con los eigenvectors de $AA^T$

$V$ es la matrix con los eigenvectors de $A^TA$

In [87]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

C = np.array([ [3,2,2], [2,3,-2] ])

SquareC = C.T @ C # multiplicacion de matrices

print("C")
print(C, "\n")
print("CT C")
print(SquareC)

C
[[ 3  2  2]
 [ 2  3 -2]] 

CT C
[[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]


La razon de usar la traspuesta
$$ C = U \Sigma V^T$$
$$ C^T C =( U \Sigma V^T)^T U \Sigma V^T$$
$$ C^T C  = V \Sigma^T U^T U \Sigma V^T = V \Sigma^T \Sigma V^T $$


Buscaremos los eigenvalues y eigenvectors de la matriz $CC^T$

In [89]:
eigenvals, eigenvecs = sp.linalg.eig(SquareC)
eigenvecs_row = eigenvecs.T # son los vectores columnas, asi que para obtener con notacion de filas

In [90]:
eigenvals = eigenvals.real
eigenvals

array([2.50000000e+01, 4.69538746e-15, 9.00000000e+00])

In [91]:
eigenvecs

array([[-7.07106781e-01, -6.66666667e-01,  2.35702260e-01],
       [-7.07106781e-01,  6.66666667e-01, -2.35702260e-01],
       [ 1.42731104e-17,  3.33333333e-01,  9.42809042e-01]])

Demostracion:
$$S \vec v = \lambda \vec v$$

In [92]:
np.round(SquareC @ eigenvecs[:,0])

array([-18., -18.,   0.])

In [93]:
np.round(eigenvals[0] * eigenvecs[:,0])

array([-18., -18.,   0.])

In [94]:
# utilizando los vectores columna originales
# al compararlo asi podemos acabar con errores, ya que hay un error de maquina
# que no son 100% precisos
SquareC @ eigenvecs[:,0] == eigenvals[0] * eigenvecs[:,0]

array([False, False, False])

In [95]:
eigenvals_C = np.sqrt(eigenvals)

V = eigenvecs
Sigma = np.diag(eigenvals_C)

hasta ahora tenemos Sigma: 
- $\Sigma$, una matriz diagonal con los eigenvalues
- $V$ Los eigenvectores

$$ C = U \Sigma V^T $$

$$ C V = U \Sigma V^T V =  U \Sigma$$

Aplicamos la inversa de $\Sigma$ que es facil
$$
\Sigma = diag( \sigma_1, \sigma_2)
$$

$$
\Sigma^{-1} = diag( \frac{1}{\sigma_1}, \frac{1}{\sigma_2})
$$

Asi encontramos U:
$$
C V \Sigma^{-1} = U \Sigma \Sigma^{-1} = U
$$

In [97]:
# calculamos C V Sigma^-1

Sigma_inv = np.diag(1/eigenvals_C)

U = C @ V @ Sigma_inv
U

array([[-7.07106781e-01, -1.62022195e-09,  7.07106781e-01],
       [-7.07106781e-01, -1.13415537e-08, -7.07106781e-01]])

In [99]:
# y asi construyo la matriz original
U @ Sigma @ V.T

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])